# Generated by Django 5.0.6 on 2024-08-25 02:11

import django.db.models.deletion
import stake.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Stake',
            fields=[
                ('id', models.CharField(default='436296', editable=False, max_length=36, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('crypto_asset', models.CharField(default='btc', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('maturity_date', models.DateTimeField(blank=True, null=True)),
                ('duration', models.CharField(max_length=30)),
                ('status', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='approved', max_length=10)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDatabase',
            fields=[
                ('id', models.CharField(default=stake.models.generate_deposit_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('btc', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('eth', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('xlm', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ltc', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('bch', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('ada', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Withdraw',
            fields=[
                ('id', models.CharField(default=stake.models.generate_deposit_id, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('crypto_asset', models.CharField(default='btc', max_length=255)),
                ('address', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
