# Generated by Django 5.0.6 on 2024-08-25 02:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stake', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stake',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
