# Generated by Django 5.0.6 on 2024-08-25 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stake', '0002_alter_stake_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stake',
            name='id',
            field=models.CharField(default='788500', editable=False, max_length=36, primary_key=True, serialize=False),
        ),
    ]
