# Generated by Django 5.0.6 on 2024-08-27 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stake', '0005_alter_stake_duration_alter_stake_id_fund'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdatabase',
            name='stake_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
